### ISSUE TITLE
What happened to .NET 4.5.2 support ?

### ISSUE THREAD

**Issue by daveaton** [stfx/innodependencyinstaller#18]
I have just upgraded my project from .NET 4.0 to 4.5.2 since 4.5.2 is the last lower supported by MS .NET Version. 

https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/

 It's 2016 and I see back in 2014 it used to be there.

https://github.com/stfx/innodependencyinstaller/commit/726fb25c432ee33ed7c963a6c0e1f674e5fcdf61

Was there any reason why we removed it ?

**Comment by daveaton** [comment]
I see what happened.  10 mo ago you got a pull request to support 4.6  what probably happened is that the person who write this updated just modified 4.5 to 4.6.

https://github.com/stfx/innodependencyinstaller/commit/fe625d5fc226f2a143b2018a5e73b50abf97360b

What I am not sure of was this accidental or on purpose?

**Comment by UeliHilfiker** [comment]
It wasn't an accidential, see pull request https://github.com/stfx/innodependencyinstaller/pull/5. 

You can use .NET 4.6 for your .NET 4.5.2 project. 
.NET 4.6.x includes the 4.5.x updates and the minimum OS version is still the same.

**Comment by daveaton** [comment]
Oh.  My theory was that 4.6 was trash (garbage collector not working correctly) and it need to be at least 4.6.1.  Even though I was targeting 4.5.2 I hoped that I would not have to install it.. maybe it was already on the user's machine.  My installer would be for those who don't have it already.  Currently all project and dependencies are currently targeting 4.5.2.   I am not sure I want to upgrade to 4.6.1 just yet.

**Comment by daveaton** [comment]
I guess I have no choice but to upgrade.
