### ISSUE TITLE
[documentation] Images holder

### ISSUE THREAD

**Issue by kungfux** [stfx/innodependencyinstaller#29]
As a part of documentation implementation, I have to migrate the images from [codeproject](https://www.codeproject.com/Articles/20868/NET-Framework-1-1-2-0-3-5-Installer-for-InnoSetup). As far the only way to use images in README.md and Wiki is to upload them to the issue and then reference in markdown. I hope nobody mind to use the issue to keep these images.

![dotnetfx_installer1](https://cloud.githubusercontent.com/assets/10548881/26322035/f8abb420-3f31-11e7-8be7-5a73aa29194b.jpg)
![dotnetfx_installer2](https://cloud.githubusercontent.com/assets/10548881/26322032/f8a87e7c-3f31-11e7-960b-1c2942f5851e.jpg)
![dotnetfx_installer3](https://cloud.githubusercontent.com/assets/10548881/26322034/f8aa3ec4-3f31-11e7-8092-868814ea3d2b.jpg)
![dotnetfx_installer4](https://cloud.githubusercontent.com/assets/10548881/26322033/f8a8d494-3f31-11e7-8526-4ea86bb1bac7.jpg)
![dotnetfx_structure](https://cloud.githubusercontent.com/assets/10548881/26322036/f8af63ea-3f31-11e7-9378-5184becc970e.jpg)

**Comment by DomGries** [comment]
<img src="https://user-images.githubusercontent.com/341158/100111333-468f2a80-2e6e-11eb-91f5-7a35bba5f5a9.PNG">
<img src="https://user-images.githubusercontent.com/341158/100111336-4727c100-2e6e-11eb-9d80-2c8696718c55.PNG">

**Comment by DomGries** [comment]
![InnoDependencyInstaller](https://user-images.githubusercontent.com/341158/122873592-3e2e9d80-d332-11eb-8055-8a4c6064ac4e.gif)
