### ISSUE TITLE
Graceful handling if the depedency cannot be downloaded

### ISSUE THREAD

**Issue by luebbe** [stfx/innodependencyinstaller#3]
Currently there is only the option to completely abort the setup if a dependency cannot be downloaded, e.g. if the computer doesn't have an internet connection (yes they exist, industry PCs for example :)).

It would be nice to either:
- be able to continue the setup even when the dependencies are missing (yes, I'll install them later. If it doesn't work it's all my fault ...)
- abort the setup as it is now, but display a message to the user that he can install the dependencies manually and re-run the setup afterwards. This message should also list the dependencies and the download URLs

I'd personally prefer the second solution, because this way you can still make sure that the dependencies are available to your application.

**Comment by kungfux** [comment]
Generally, you can distribute the offline installations for necessary dependencies by putting them into bin/MyProgramDependencies folder if you are going to run setup on PCs without an internet connection.

Regarding your second concern, the code contains following message stating that dependencies may be installed manually, but I am not sure at what exact point it may appear.

> en.depinstall_error=An error occured while installing the dependencies. Please restart the computer and run the setup again or install the following dependencies manually:%n

I do not like that user has no possibility to continue installation as well, but the program will not work if we will allow to install our program without dependencies anyway. For now, I distribute my apps in two formats: zip archive and setup executable to handle this situation.

**Comment by stfx** [comment]
You can also package dependencies within the setup as is shown in https://github.com/stfx/innodependencyinstaller/blob/master/scripts/products/directxruntime.iss

**Comment by stfx** [comment]
I just pushed a commit which resolves this by showing an error message with `retry`, `ignore` and `abort` buttons. The latter should work how it was before, `retry` tries to install the product again and `ignore` skips installing that product to make sure the user is always able to finish it and later install the missing dependencies manually.

@luebbe @kungfux Please test it and let me know how it works now. Thanks!
