### ISSUE TITLE
.net 4.5 and 4.5.2 are missing

### ISSUE THREAD

**Issue by nmg196** [stfx/innodependencyinstaller#30]
Hi, I can see on Codeproject it says 4.5.2 is supported, but there is no script for this. How would I install 4.5.2?

**Comment by kungfux** [comment]
Hello, please take a look at issue #18? It looks pretty similar to yours.

**Comment by nmg196** [comment]
Thanks.. I think I can get away with installing 4.6 as long as this only triggers if 4.5.2 isn't already installed.
