### ISSUE TITLE
.NET 4.7 download link

### ISSUE THREAD

**Issue by RickZeeland** [stfx/innodependencyinstaller#34]
Anybody has any idea what the download link for **.NET framework 4.7** is ?
I found this one, but don't think that it is the correct one for InnoSetup:
[https://www.microsoft.com/en-us/download/confirmation.aspx?id=55170](url)

Update: found it on: [https://packetstormsecurity.com/files/143218/Microsoft-.NET-Framework-4.7-DLL-Hijacking.html](url)

<https://download.microsoft.com/download/A/E/A/AEAE0F3F-96E9-4711-AADA-5E35EF902306/NDP47-KB3186500-Web.exe>,
   <https://download.microsoft.com/download/D/D/3/DD35CC25-6E9C-484B-A746-C5BE0C923290/NDP47-KB3186497-x86-x64-AllOS-ENU.exe>,
   <https://download.microsoft.com/download/8/3/8/838A8A52-67BA-4F1C-BA95-FABBA994352C/NDP47-KB3186497-x86-x64-AllOS-DEU.exe>,

**Comment by stfx** [comment]
Look at the following post to see how you can find the download links: https://github.com/stfx/innodependencyinstaller/issues/9#issuecomment-231405801
