### ISSUE TITLE
Unknown identifier 'msiproductupgrade' when using #define use_vc2017

### ISSUE THREAD

**Issue by zoenie123** [stfx/innodependencyinstaller#36]
Hi, I downloaded the code and tried to compile with only #define use_vc2017 enabled.
It gives me the following error:

```
File:
C:\xxxxx\scripts\vcredist2017.iss
Line 22:
Column 11:
Unknown identifier 'msiproductupgrade'
```

Innosetup version is 5.5.4 (u) and I also tried 5.5.9 (u).
Any idea what could cause this?

**Comment by kungfux** [comment]
Hi @zoenie123, it seems _vsredist2017.iss_ depends on _msiproduct.iss_. So, you have to include it as well by defining it as
```
#define use_msiproduct
```

**Comment by kungfux** [comment]
There are not only product files that may be included but common/shared files as well, so please be aware of this.

**Comment by zoenie123** [comment]
It was that simple, thanks!
