### ISSUE TITLE
Only the vcredist2017_x64.exe installs on a 64bit system

### ISSUE THREAD

**Issue by zoenie123** [stfx/innodependencyinstaller#37]
I want the vcredist2017.exe (32bit) to be installed on my 64bit system.
When I run the script with the #define use_msiproduct and #define use_vc2017 it only installed the 64bit version of the C++ redistributables.
In order to run 32 bit executables on a 64 bit system the 32bit runtime needs to be installed on the 64bit system.
I have the suspicion that the script checks if the target system is 32 bit and then installs the 32bit runtime and also if the target system is 64 bit and then installs the 64 bit runtime, but actually both runtimes should be installed on a 64 bit system to be able to run both 32 bit and 64 bit executables.
Am I correct that this is the way how the script works? And how can I change the script to install both of them in case of a 64bit system?

**Comment by kungfux** [comment]
> I have the suspicion that the script checks if the target system is 32 bit and then installs the 32bit runtime and also if the target system is 64 bit and then installs the 64 bit runtime...

That's correct.

**Comment by zoenie123** [comment]
And how can I change the script to install both of them in case of a 64bit system? Because this is really what is needed for 32 bits executables.

**Comment by kungfux** [comment]
Well, it seems that authors assumed this might be useful. Please take a look at `scripts/products.pas`, it contains procedure `SetForceX86(value: boolean);` that you are looking for. I think you may try to edit your local copy of `scripts/products/vcredist2017.iss` and call that procedure before installing vcredist2017. This should force installing x32 version on the x64 system.

**Comment by zoenie123** [comment]
Ok, thanks. Useful information. I will have a look.

**Comment by kungfux** [comment]
Please take a look for example right in the main `setup.iss` file:

```
#ifdef use_vc2013
	//SetForceX86(true); // force 32-bit install of next products
	vcredist2013('12'); // min allowed version is 12.0
	//SetForceX86(false); // disable forced 32-bit install again
#endif
```

Maybe you can play with it and call a proper installation two times with `SetForceX86(true)` and then with `SetForceX86(false)` like in that example.

**Comment by zoenie123** [comment]
And the answer is this:
```
#ifdef use_vc2017
	SetForceX86(true); // force 32-bit install of next products
	vcredist2017('14'); // min allowed version is 14.0
	SetForceX86(false); // disable forced 32-bit install again
	vcredist2017('14'); // min allowed version is 14.0
#endif
```
It works perfectly.
