### ISSUE TITLE
.NET Framework 4.6 installing dependency error

### ISSUE THREAD

**Issue by jesusvpct** [stfx/innodependencyinstaller#7]
When running my setup, dependency of .NET 4.6 is detected, but when is installing, it shows a window with information helper, like running the file from command line NDP46-KB3045560-Web.exe /?

Why it's not working?

**Comment by jesusvpct** [comment]
It seems the problem is the combination of parameters /q /passive
Trying on my computer from command line, that combination shows that window. It seems a problem with the .net installer.

**Comment by stfx** [comment]
Try changing to `/passive /norestart` then and let me know if that requires any user interaction (should not) and still shows the UI of the installer (should)

**Comment by jesusvpct** [comment]
That works. It shows the .NET Window installation, but works!
![2015-09-03_14-37-39](https://cloud.githubusercontent.com/assets/5315258/9658397/49609534-5249-11e5-9fa3-635534acce46.png)

**Comment by stfx** [comment]
Thanks, you can use `/q` indead of `/passive` if you dont want to show the UI but I prefer the latter

**Comment by jesusvpct** [comment]
Never mind, i like your siguestion. It works fine forma me! Thanks!
