### ISSUE TITLE
Error when newer visual studio 2015 runtimes are installed

### ISSUE THREAD

**Issue by myrsloik** [stfx/innodependencyinstaller#9]
If a newer version of the vs2015 runtimes are installed (for example update 1) then installation will fail. The proper solution seems to be to consider return code 1638 (another copy already installed) as success as well. In my testing it only happens when a newer version than the one trying to be installed is present. If an older version is present it's simply updated.

I suspect this could apply to vs2012-2013 as well but didn't try to verify it.

As a bonus, updated source lines for vs2015 update1 runtimes:
vcredist2015_url = 'http://download.microsoft.com/download/C/E/5/CE514EAE-78A8-4381-86E8-29108D78DBD4/VC_redist.x86.exe';
vcredist2015_url_x64 = 'http://download.microsoft.com/download/C/E/5/CE514EAE-78A8-4381-86E8-29108D78DBD4/VC_redist.x64.exe';

vcredist2015_productcode = '{1045AB6F-6151-3634-8C2C-EE308AA1A6A7}';
vcredist2015_productcode_x64 = '{B0B194F8-E0CE-33FE-AA11-636428A4B73D}';

**Comment by retrorich75** [comment]
Hi mysloik, your GUID are wrong for me my code is like this;

`// Richard M Parslow 28/02/2015
// requires Windows 10, Windows 7 Service Pack 1, Windows 8, Windows 8.1, Windows Server 2003 Service Pack 2, Windows Server 2008 R2 SP1, Windows Server 2008 Service Pack 2, Windows Server 2012, Windows Vista Service Pack 2, Windows XP Service Pack 3
// http://www.microsoft.com/en-us/download/details.aspx?id=49984
// Additional Prerequisite: April 2014 Update (see KB 2919355) and Servicing Stack Update (see KB 2919442 or later) for Windows 8.1 and Windows Server 2012 R2.

[CustomMessages]
vcredist2015up1_title=Visual C++ Redistributable for Visual Studio 2015 Update 1
vcredist2015up1_title_x64=Visual C++ Redistributable for Visual Studio 2015 Update 1 64-Bit

; Version: 2015 - Date Published: 17th of November 2015

en.vcredist2015up1_size=13.3 MB
de.vcredist2015up1_size=13,3 MB
fr.vcredist2015up1_size=13,3 Mo
it.vcredist2015up1_size=13,3 MB
pl.vcredist2015up1_size=13,3 MB

en.vcredist2015up1_size_x64=14.1 MB
de.vcredist2015up1_size_x64=14,1 MB
fr.vcredist2015up1_size_x64=14,1 Mo
it.vcredist2015up1_size_x64=14,1 MB
pl.vcredist2015up1_size_x64=14,1 MB


[Code]
const


  vcredist2015up1_url = 'http://download.microsoft.com/download/C/E/5/CE514EAE-78A8-4381-86E8-29108D78DBD4/VC_redist.x86.exe';
  vcredist2015up1_url_x64 = 'http://download.microsoft.com/download/C/E/5/CE514EAE-78A8-4381-86E8-29108D78DBD4/VC_redist.x64.exe';

	vcredist2015up1_productcode = '{65AD78AD-D23D-3A1E-9305-3AE65CD522C2}';
	vcredist2015up1_productcode_x64 = '{A1C31BA5-5438-3A07-9EEE-A5FB2D0FDE36}';

procedure vcredist2015up1();
begin
	if (not IsIA64()) then begin
		if (not msiproduct(GetString(vcredist2015up1_productcode, vcredist2015up1_productcode_x64, ''))) then
			AddProduct('vcredist2015up1' + GetArchitectureString() + '.exe',
				'/passive /norestart',
				CustomMessage('vcredist2015up1_title' + GetArchitectureString()),
				CustomMessage('vcredist2015up1_size' + GetArchitectureString()),
				GetString(vcredist2015up1_url, vcredist2015up1_url_x64, ''),
				false, false);
	end;
end;
`
Of course I also updated setup.iss and products.iss with '#include "isxdl\isxdl.iss"

[CustomMessages]
DependenciesDir=MyProgramDependencies

en.depdownload_msg=The following applications are required before setup can continue:%n%n%1%nDownload and install now?
de.depdownload_msg=Die folgenden Programme werden benötigt bevor das Setup fortfahren kann:%n%n%1%nJetzt downloaden und installieren?
fr.depdownload_msg=Les applications suivantes sont nécessaires avant l'installation peut continuer:%n%n%1%nTéléchargement et installer maintenant? 
it.depdownload_msg=Le seguenti applicazioni sono necessari per continuare l'installazione:%n%n%1%nScarica ed installare ora?
nl.depdownload_msg=De volgende toepassingen zijn nodig vóór de installatie kunt doorgaan:%n%n%1%nDownload en installeer nu?
pl.depdownload_msg=Ponizsze aplikacje sa wymagane przed konfiguracji moze kontynuowac:%n%n%1%nPobierz i zainstalowac teraz?

en.depdownload_memo_title=Download dependencies
de.depdownload_memo_title=Abhängigkeiten downloaden
fr.depdownload_memo_title=Télécharger les dépendances
it.depdownload_memo_title=Scarica le dipendenze
nl.depdownload_memo_title=Download afhankelijkheden
pl.depdownload_memo_title=Pobierz zaleznosci

en.depinstall_memo_title=Install dependencies
de.depinstall_memo_title=Abhängigkeiten installieren
fr.depinstall_memo_title=Installez les dépendances
it.depinstall_memo_title=installare le dipendenze
nl.depinstall_memo_title=Installeer afhankelijkheden
pl.depinstall_memo_title=Instalowanie zaleznosciami

en.depinstall_title=Installing dependencies
de.depinstall_title=Installiere Abhängigkeiten
fr.depinstall_title=Installation des dépendances
it.depinstall_title=installare le dipendenze
nl.depinstall_title=Installeer afhankelijkheden
pl.depinstall_title=Instalowanie zaleznosciami

en.depinstall_description=Please wait while Setup installs dependencies on your computer.
de.depinstall_description=Warten Sie bitte während Abhängigkeiten auf Ihrem Computer installiert wird.
fr.depinstall_description=S'il vous plaît patienter pendant que le programme d'installation installe les dépendances sur votre ordinateur.
it.depinstall_description=Per favore attendi che viene installato sul computer dipendenze.
nl.depinstall_description=Een moment geduld aub Setup installeert afhankelijkheden op uw computer.
pl.depinstall_description=Poczekaj Instalator instaluje zaleznosci na komputerze.

en.depinstall_status=Installing %1...
de.depinstall_status=Installiere %1...
fr.depinstall_status=Installation %1...
it.depinstall_status=installazione %1...
nl.depinstall_status=Installeren %1...
pl.depinstall_status=Instalacja %1....

en.depinstall_missing=%1 must be installed before setup can continue. Please install %1 and run Setup again.
de.depinstall_missing=%1 muss installiert werden bevor das Setup fortfahren kann. Bitte installieren Sie %1 und starten Sie das Setup erneut.
fr.depinstall_missing=%1 doit être installé avant l'installation peut continuer. S'il vous plaît installer %1 et exécutez à nouveau le programme d'installation.
it.depinstall_missing=%1 deve essere installato per continuare l'installazione. Si prega di installare %1 ed eseguire nuovamente l'installazione.
nl.depinstall_missing=%1 moet worden geïnstalleerd vóór de installatie kan worden voortgezet. Installeer %1 en voer Setup opnieuw uit.
pl.depinstall_missing=%1 musi byc zainstalowany przed konfiguracja moze byc kontynuowana. Prosze zainstalowac %1 i ponownie uruchomic program instalacyjny.

en.depinstall_error=An error occured while installing the dependencies. Please restart the computer and run the setup again or install the following dependencies manually:%n
de.depinstall_error=Ein Fehler ist während der Installation der Abghängigkeiten aufgetreten. Bitte starten Sie den Computer neu und führen Sie das Setup erneut aus oder installieren Sie die folgenden Abhängigkeiten per Hand:%n
fr.depinstall_error=Une erreur est survenue lors de l'installation des dépendances . S'il vous plaît redémarrer l'ordinateur et exécuter à nouveau le programme d'installation ou installer les dépendances suivantes manuellement:%n
it.depinstall_error=È verificato un errore durante l'installazione le dipendenze . Si prega di riavviare il computer ed eseguire nuovamente la configurazione o installare le seguenti dipendenze manualmente:%n
nl.depinstall_error=Er is een fout opgetreden tijdens het installeren van de afhankelijkheden. Gelieve de computer opnieuw op en voer de installatie opnieuw uit of de volgende afhankelijkheden handmatig installeren:%n
pl.depinstall_error=Wystapil blad podczas instalowania zaleznosci. Uruchom ponownie komputer, a nastepnie ponownie uruchomic setup lub recznie zainstalowac nastepujace zaleznosci:%n

en.isxdl_langfile=
de.isxdl_langfile=german2.ini
fr.isxdl_langfile=french3.ini
it.isxdl_langfile=italian.ini
nl.isxdl_langfile=dutch.ini
pl.isxdl_langfile=polish.ini


[Files]
Source: "scripts\isxdl\german2.ini"; Flags: dontcopy
Source: "scripts\isxdl\french3.ini"; Flags: dontcopy
Source: "scripts\isxdl\italian.ini"; Flags: dontcopy
Source: "scripts\isxdl\dutch.ini"; Flags: dontcopy
Source: "scripts\isxdl\polish.ini"; Flags: dontcopy'

	vcredist2015up1_productcode = '{65AD78AD-D23D-3A1E-9305-3AE65CD522C2}';
	vcredist2015up1_productcode_x64 = '{A1C31BA5-5438-3A07-9EEE-A5FB2D0FDE36}';

procedure vcredist2015up1();
begin
	if (not IsIA64()) then begin
		if (not msiproduct(GetString(vcredist2015up1_productcode, vcredist2015up1_productcode_x64, ''))) then
			AddProduct('vcredist2015up1' + GetArchitectureString() + '.exe',
				'/passive /norestart',
				CustomMessage('vcredist2015up1_title' + GetArchitectureString()),
				CustomMessage('vcredist2015up1_size' + GetArchitectureString()),
				GetString(vcredist2015up1_url, vcredist2015up1_url_x64, ''),
				false, false);
	end;
end;
`
Of course I also updated setup.iss with '#define use_vc2015up1' and products.iss and created the corresponding language files, all my work in my fork, free for all ;-)

**Comment by Deadpikle** [comment]
Note that as of Visual Studio 2015 Update 2, there is a new C++ redistributable. Haven't managed to find it online yet, but the GUIDs are:
```
vcredist2015up2_productcode = '{B5FC62F5-A367-37A5-9FD2-A6E137C0096F}';
vcredist2015up2_productcode_x64 = '{7B50D081-E670-3B43-A460-0E2CDB5CE984}';
```
See also [here](https://www.visualstudio.com/en-us/downloads/update2-prereleases#AdditionalPageSections_67).

**Comment by retrorich75** [comment]
@Deadpikle these are only Release Candidates ie Microsoft Visual C++ 2015 Redistributable Update 2 RC see https://www.visualstudio.com/en-us/downloads/update2-prereleases

**Comment by Deadpikle** [comment]
@retorich75 Right, but for those of us who have VS 2015 Update 2 installed, we have said RC, so InnoSetup dependency management will still throw "You need to install Update 1!" if you don't use the latest product codes at the very least.

We'll have to wait for the non-RC versions to come out to do a VS 2015 C++ Update 2 pull request.

**Comment by daveaton** [comment]
Any Update on this... VS C++ Update 3 is now out.   https://blogs.msdn.microsoft.com/chuckw/2016/06/27/visual-studio-2015-update-3/

**Comment by WildCard-25** [comment]
Using Chrome :-

Open Microsoft Visual C++ 2015 Redistributable Page
https://www.visualstudio.com/downloads/download-visual-studio-vs#d-visual-c

Microsoft Visual C++ 2015 Redistributable Update 3

Choose format x86
Click download

Click Chrome's "Show all downloads"
Right-Click on download link and select 'Copy link address'
change 'http' to 'https'
https://download.microsoft.com/download/d/e/c/dec58546-c2f5-40a7-b38e-4df8d60b9764/vc_redist.x86.exe

Choose format x64
Click download

Click Chrome's "Show all downloads"
Right-Click on download link and select 'Copy link address'
change 'http' to 'https'
https://download.microsoft.com/download/2/c/6/2c675af0-2155-4961-b32e-289d7addfcec/vc_redist.x64.exe


Using Explorer :-
Run 'vc_redist.x86.exe'
Get version info
14.0.24210

After installing change to your temp directory (ie. "C:\Users\Username\AppData\Local\Temp")
Open RuntimeMinimum install log (ie. dd_vcredist_x86_20160709013201_000_vcRuntimeMinimum_x86.log)
Get product code from msi location line, about 4 lines down (ie.  ******* Product: C:\ProgramData\Package Cache\{8FD71E98-EE44-3844-9DAD-9CB0BBBC603C}v14.0.24210\packages\vcRuntimeMinimum_x86\vc_runtimeMinimum_x86.msi)
{8FD71E98-EE44-3844-9DAD-9CB0BBBC603C}

Or you can uninstall it instead and the line will be ******* Product: {8FD71E98-EE44-3844-9DAD-9CB0BBBC603C}

Do the same for 'vc_redist.x64.exe'
14.0.24210
{C0B2C673-ECAA-372D-94E5-E89440D087AD}

Update install file.

**Comment by WildCard-25** [comment]
This won't stop installer from crashing if a newer version is already installed though.
My setup is a little different, but this should be close (works for me, but I may have introduced errors cutting and pasting to look similar to existing code) :-)

add to end of msiproducts.iss
```

function MsiEnumRelatedProducts(szUpgradeCode: String; nReserved: DWORD; nIndex: DWORD; szProductCode: String): Integer;
external 'MsiEnumRelatedProducts{#AW}@msi.dll stdcall';

function MsiGetProductInfo(szProductCode: String; szProperty: String; szValue: String; var nValueBufSize: DWORD): Integer;
external 'MsiGetProductInfo{#AW}@msi.dll stdcall';

function MsiProductInstalled(szUpgradeCode: String; nProductVersion: DWORD): Boolean;
var
	szProductCode, szValue, szBuild: String;
	nValueBufSize, nBuild: DWORD;
begin
	SetLength( szProductCode, 39 );
	SetLength( szValue, 39 );
	nValueBufSize := Length( szValue );
	Result := false;

	if ( MsiEnumRelatedProducts( szUpgradeCode, 0, 0, szProductCode ) = 0 ) then begin
		if ( MsiGetProductInfo( szProductCode, 'VersionString', szValue, nValueBufSize ) = 0 ) then begin
			szBuild := ExtractFileExt( szValue );
			szBuild := Copy( szBuild, 2, Length( szBuild ) - 1 );
			nBuild := StrToInt( szBuild );
			if ( nBuild >= nProductVersion ) then begin
				Result := true;
			end;
		end;
	end;
end;
```

replace vcredist2015.iss with
```
// requires Windows 10, Windows 7 Service Pack 1, Windows 8, Windows 8.1, Windows Server 2003 Service Pack 2, Windows Server 2008 R2 SP1, Windows Server 2008 Service Pack 2, Windows Server 2012, Windows Vista Service Pack 2, Windows XP Service Pack 3

// Visual C++ Redistributable for Visual Studio 2015 Update 3 (14.0.24210)
// https://www.visualstudio.com/downloads/download-visual-studio-vs#d-visual-c

[CustomMessages]
vcredist2015_title=Microsoft Visual C++ 2015 Update 3 Redistributable (x86)
vcredist2015_title_x64=Microsoft Visual C++ 2015 Update 3 Redistributable (x64)

en.vcredist2015_size=13.7 MB
de.vcredist2015_size=13,7 MB

en.vcredist2015_size_x64=14.5 MB
de.vcredist2015_size_x64=14,5 MB


[Code]
const
  vcredist_version_major = 14;
  vcredist_version_minor = 0;
  vcredist_version_build = 24210;

	vcredist2015_url = 'https://download.microsoft.com/download/d/e/c/dec58546-c2f5-40a7-b38e-4df8d60b9764/vc_redist.x86.exe';
	vcredist2015_url_x64 = 'https://download.microsoft.com/download/2/c/6/2c675af0-2155-4961-b32e-289d7addfcec/vc_redist.x64.exe';

	vcredist2015_productcode = '{8FD71E98-EE44-3844-9DAD-9CB0BBBC603C}';
	vcredist2015_productcode_x64 = '{C0B2C673-ECAA-372D-94E5-E89440D087AD}';

  vcredist2015_upgradecode = '{65E5BD06-6392-3027-8C26-853107D3CF1A}';
  vcredist2015_upgradecode_x64 = '{36F68A90-239C-34DF-B58C-64B30153CE35}';

procedure vcredist2015();
begin
	if (not IsIA64()) then begin
		if (not MsiProductInstalled(GetString(vcredist2015_upgradecode, vcredist2015_upgradecode_x64, ''), vcredist_version_build)) then
			AddProduct('vcredist2015' + GetArchitectureString() + '.exe',
				'/passive /norestart',
				CustomMessage('vcredist2015_title' + GetArchitectureString()),
				CustomMessage('vcredist2015_size' + GetArchitectureString()),
				GetString(vcredist2015_url, vcredist2015_url_x64, ''),
				false, false);
	end;
end;
```

Upgrade code can be found by looking in the RuntimeMinimum install log and searching for 'UpgradeCode'

x86
{65E5BD06-6392-3027-8C26-853107D3CF1A}

x64
{36F68A90-239C-34DF-B58C-64B30153CE35}
